# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_menuitem_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='capacity',
            field=models.PositiveIntegerField(default=4, help_text='Number of guests'),
        ),
    ]
