# Generated by Django 6.0 on 2026-02-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_table_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='x_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='table',
            name='y_position',
            field=models.IntegerField(default=0),
        ),
    ]
