# Generated by Django 6.0 on 2026-02-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_restaurant_closing_time_restaurant_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
