# Generated by Django 6.0.2 on 2026-02-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_restaurant_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('restaurant_admin', 'Restaurant Admin'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
